server:
  port:
    8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cartify_auth
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka